server:
  port: 10003
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: jypj-admin
          uri: lb://jypj-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8001/nacos/
    routes:
      - name: 后台管理服务
        serviceName: jypj-admin
        location: /v2/api-docs?group=default
        servicePath: /admin
      - name: 绩效考评系统服务
        serviceName: jypj-achievement
        location: /v2/api-docs?group=default
        servicePath: /achievement
